### ISSUE TITLE
HELP ME about JSONField when build_schema_mutation()

### ISSUE THREAD

**Issue by snilli** [yefeza/django-graphbox#6]
<img width="980" alt="image" src="https://github.com/yefeza/django-graphbox/assets/34303427/bc79d789-aa9b-4d2b-9fd0-5a627ab780c4">

I thing it not found in model type dict  please fix this for support  json field and OnotoOnoFiled
<img width="887" alt="image" src="https://github.com/yefeza/django-graphbox/assets/34303427/a9b297e4-afe3-45f1-b2b7-100195e968ff">

**Comment by yefeza** [comment]
JSONField and OneToOneField was not supported. Now is supported on new release 1.2.5 #7
